[nspr] Set build time based on changelog. Fixes JB#59611
sailfishos/nspr pull request #1
Opened 2022-12-12 14:45 UTC by mlehtima

2022-12-12 20:02 UTC, Thaodan requested changes
See question.

2022-12-12 20:02 UTC, Thaodan commented on nspr.spec
> +make SH_DATE="$BUILD_STRING" SH_NOW="$BUILD_TIME" %{?_smp_mflags}
Why did you remove %make_build here? it does accept arguments.

2022-12-13 00:14 UTC, mlehtima commented on nspr.spec
> +make SH_DATE="$BUILD_STRING" SH_NOW="$BUILD_TIME" %{?_smp_mflags}
Changed it back.

2022-12-13 06:16 UTC, vigejolla approved these changes
LGTM

2022-12-13 06:38 UTC, martyone approved these changes

2022-12-13 10:08 UTC, Thaodan approved these changes
LGTM

2022-12-13 14:08 UTC, merged